run:
  timeout: 5m
  skip-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - gci
    - unparam
    - unused
#    - errcheck
#    - gosimple
#    - ineffassign
#    - staticcheck
#    - structcheck
#    - typecheck
#    - varcheck

linters-settings:
  gci:
    no-inline-comments: true
    no-prefix-comments: true
    sections:
      - standard
      - default
      - prefix(github.com/suborbital)
