project_name: e2core
env:
  - CGO_ENABLED=1
builds:
  - id: e2core
    main: .
    binary: e2core
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - netgo
    overrides:
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
        ldflags:
          - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
          - -extldflags "-static"
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
        ldflags:
          - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
          - -extldflags "-static"
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=oa64-clang
          - CXX=oa64-clang++

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'

archives:
  - id: e2core
    name_template: 'e2core-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    builds:
      - e2core
