version: "3.9"
services:
  linter:
    container_name: "e2core_linter"
    image: "golangci/golangci-lint:v1.52-alpine"
    volumes:
      - .:/app
    working_dir: /app
    command: golangci-lint run -v ./...

  lintfixer:
    container_name: "e2core_lintfixer"
    image: "golangci/golangci-lint:v1.52-alpine"
    volumes:
      - .:/app
    working_dir: /app
    command: golangci-lint run -v --fix ./...
