FROM golang:1.17 as builder

RUN mkdir -p /go/src/github.com/suborbital/atmo
COPY . /go/src/github.com/suborbital/atmo/
WORKDIR /go/src/github.com/suborbital/atmo/

RUN go install -tags proxy

FROM debian:buster-slim

RUN groupadd -g 999 atmo && \
    useradd -r -u 999 -g atmo atmo && \
	mkdir -p /home/atmo && \
	chown -R atmo /home/atmo && \
	chmod -R 700 /home/atmo

RUN apt-get update \
	&& apt-get install -y ca-certificates

# atmo binary
COPY --from=builder /go/bin/atmo /usr/local/bin/atmo-proxy

WORKDIR /home/atmo

USER atmo