name: ci

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod download

      - run: make e2core/install
      - run: make e2core/static
      - run: make test/ci

  image:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: docker_meta
        with:
          images: suborbital/e2core,ghcr.io/suborbital/e2core
          tags: |
            type=match,pattern=(v.*)
          flavor: |
            latest=auto

      - name: Build e2core image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          load: true
          push: false
          tags: suborbital/e2core:dev
      - run: docker run --rm suborbital/e2core:dev /usr/local/bin/e2core -v

      - name: Build and push e2core image
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  release-bin:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, lint]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:v1.19

    steps:
      - uses: actions/checkout@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
